Makefile
pigpio.c

I am using pigpio by embedding it in the Erlang VM in Elixir. The current behavior does not allow clean integration because:
1) It overrides the signal handlers set by the virtual machine
2) Outputs on stderr
I added a compilation flag to modify this behavior, -DEMBEDDED_IN_VM

add EMBEDDED_IN_VM compilation flag to remove debugging and signal handling

---

command.c
pigpio.3
pigpio.c
pigpio.h
pigpio.py
pigpiod_if.3
pigpiod_if.c
pigpiod_if.h
pigs.1

Adds new function, gpioSerialReadInvert(), to configure normal or inverted serial logic for bit bang serial reads.
Created new configuration function/command to avoid changing the call parameters/interface of existing functions/commands.
Unsure of the policy for changing command numbers within pigpio.h, selected free number to avoid changing existing command numbers.

Option to invert bit bang serial logic.

---

pigpiod.c

I have always difficulties to determine whether my installed gpiod needs update or not. A simple output of the version string would help a lot.

Include version in help text to make identification easier.

---

pigpio.c

This flag might be defined to turn off initialization checks for serial-only tests.
The serial port functions do not require GPIO initialization.
While it is reasonable to check for initialization on the target, these checks prevent the serial functions from being tested on a PC which lacks the mapped GPIOs.

Introduced DISABLE_SER_CHECK_INITED

---

EXAMPLES/Python/GPIO_STATUS/gpio_status.py

The example `EXAMPLES/Python/GPIO_STATUS/gpio_status.py`  fails on Python3
```
Traceback (most recent call last):
File "EXAMPLES/Python/GPIO_STATUS/gpio_status.py", line 49, in <module>
stdscr.addstr(row, col, "{:2}".format(g), curses.A_BOLD)
TypeError: integer argument expected, got float
```
because in Python3 `col = (g / 11) * 25` is a `float` and not an `int`. 
I also added an explicit `sys.exit(1)` if no connection can be established to avoid nasty traceback.

small bug fix for python example

---

command.c

In the "glossary" part of the command.c file a mention of "GPIO Bank
2" should refer to "GPIO Bank 1".
Signed-off-by: Stephen Lyons <slysven@virginmedia.com>

BugFix: a typo

---

EXAMPLES/Python/DHT22_AM2302_SENSOR/DHT22.py

Improved readability by making some typographic changes to `DHT22.py` conform pep8:
* inline comments should be preceded by at least two spaces
* operators should be surrounded by whitespace
* comparison to `None` should take the general form `if cond is not None:` i.s.o. `if cond != None:`

Small editorial changes to conform to pep8

---

.gitignore
Makefile

This simplifies cross-compilation by cleaning up redundancies in vars, making stripping explicit (rather than done by install), and adding a CROSS_PREFIX var to simplify configuration.  Now, to cross-compile for Raspberry Pi, run:
make CROSS_PREFIX=arm-linux-gnueabi-
sudo make prefix=/usr/arm-linux-gnueabi install
Closes #91

Simplify cross-compilation

---

pigpio.h
pigpiod.c

Use `-g` to run pigpiod in the foreground (without forking a child process).
Ctrl+C to terminate.
Useful for modern init systems and Docker containers.
For #92.

add option for running in foreground

---

.gitignore

These get created when running `sudo python setup.py install` - best to make sure they don't get added to the repo by mistake.

Add pycache and build to .gitignore

---

pigpio.c
pigpio.py

It would be nice if IPv6 was supported.
This PR shows a possible minimal implementation.
(Currently without support for IPv6-address ACLs, and without an option to specify on which interface to listen exactly.)

Add basic IPv6 support

---

command.c
pigpio.3
pigpio.c
pigpio.h
pigpio.py
pigpiod.c

I use the pigpio library only to transmit 433MHz codes of a remote control.
To optimize CPU usage I added a new command line option "-m" for the pigpiod daemon.
This option disables the alerts thread and reduces CPU usage from 6-7% to 1.5% on my RPI 2.
It would be great when you could merge this to master.

Additional pigpiod command line option "-m" to disable the alerts

---

util/pigpiod.service

This PR adds a pigpiod.service file in the `util` directory.
This file can be installed in `/usr/lib/systemd/system` on systemd-enabled systems to add a `pigpiod` service that can be used to manage the pigpiod daemon.

Add systemd service file

---

Makefile
pigpio.c
pigpio.h

Previously with PR https://github.com/joan2937/pigpio/pull/8 the lib can be conditionnaly compiled to remove signal handling.
This PR allows to configure this behavior before library is initialized.
We use the internal cfg bit `1<<10`: 1=Handle signals (default), 0=Do not handle signals (as if previously compiled with `EMBEDDED_IN_VM`.
Flag can be changed before calling `gpioInitialise`.

Allow to configure internals to remove signals handling

---

util/Findpigpio.cmake

The Findpigpio.cmake script doesn't work for me if this is missing (CMake 3.9.4 on Arch Linux ARM).

cmake: include find_package_handle_standard_args

---

command.c
pigpio.c

This is a simple hack to allow the 3rd operand of certain 3-op commands to be a register (v? / p?) rather than only a constant.  We utilize the previously-ignored opt[3] field for this purpose.  In my application this allows me to use the HP command with script-controlled duty cycle.
This change is entirely backward-compatible; no existing programs or scripts should be affected in any way.

Allow 3-op script cmds to use regs as 3rd operand.

---

pigpio.py

I found that if the server side dropped out, you will get an exception and the lock is not released.  If you attempt to make a subsequent call that tries to use the socket, it will simply hang waiting indefinitely to acquire a lock that will not be released.  Wrapping the socket calls in a try block, and having the except block release the lock, then re-raise the exception gets around this issue.

Ensure the lock is released if there is an exception on socket I/O.

---

pigpio.c

This patch allows `reportedLevel` to be in sync with pin states just prior to starting alert notifications.  In my testing this seems to only be a problem in the first minute from starting the pigpio daemon - perhaps because the keep-alive packets have started the monitoring of pin levels.
The change seems innocuous but it would be appreciated if you could run a regression test to make sure it doesn't break anything.  I didn't provide a test script to validate results before and after applying the patch as it isn't easily extracted from my project.  I'll do so if you require a script before accepting this PR.

Update reportedLevels prior to monitoring bits

---

Makefile

This pull request contains three commits.
The first adds soversions to the shared libraries to comply with normal practice on unix-like systems and more specifically with Debian policy on shared libraries. I have started the soversion with a version of 1 but if you prefer to use some other number for the soversion that is fine too.
The second fixes the DESTDIR parameter in the install and uninstall targets so that the also install/uninstall the python stuff from the DESTDIR
The third makes "make uninstall" remove the library man pages which were left behind before.

introduce sonames and fix make install/uninstall

---

Makefile
command.c
command.h
pigpio.c
pigs.c

These commits add code to check if the device is actually a raspberry pi and fix a bunch of 64-bit cleanliness issues in the code.
Note after making these fixes I tried to test on a Debian arm64 system, but I found that Debian kernels lack a feature needed for pigpio. At this time I have not tested on a "downstream" arm64 kernel.

Pi detection and 64-bit cleanliness

---

CMakeLists.txt

As it is stated in CMake docs `SHARED` parameter is given to `add_library()`, when variable `BUILD_SHARED_LIBS` is `ON`. So now as before CMake will configure the Makefile to build shared libraries by default and if we want to build them as static, we just have to pass `-DBUILD_SHARED_LIBS=OFF` to CMake command line.
Also quote from `add_library()` docs:
> For `SHARED` and `MODULE` libraries the `POSITION_INDEPENDENT_CODE` target property is set to `ON` automatically.

Add option to build the libraries statically

---

pigpio.c

Hi,
I got pigpio working on my new RPI4 Model B running tumbleweed (arm64!) after some patches.
1. Detection added.
2. There is a bug for arm64 in pthSocketThreadHandler.
You seem to send four integers as base messages.
These are declared as an array of four uintptr_t and recv() writes 16 bytes directly into that array.
This works for arm32, where uintptr_t is 32 bit (4×4=16), but breaks arm64 (8×4=32).
The patch reads 4 uint32_t and places them in the uintptr_t array.
It is a workaround.
Better also add ntohl()s, as arm can run in LE or BE.
BR Alex Simon

Add support for arm64 and RPi4 model B

---

pigpio.c

The 55d8b880fca26ccf4b897bca1fe66796b9972345 commit on the original pigpio repo fixed parsing data received from a socket on 64bit systems.
This one fixes also the response that is being sent back to the socket - 64bit array is translated back to a 32bit array that is passed to the send function.

Fix network communication on arm64 - fix response building

---

pigpio.c

Don't try to `fclose` a `NULL` and `SIGSEGV`.

Fix broken close handling

---

pigpio.c
pigpio.h

Joan, with your review and approval, V74 is ready to merge to the master branch.  I plan to do this next week (Feb).
This release contains the following changes:
1. Mea culpa, this change initializes the parameter for setsockopt() to enable address reuse.  Issues #274 and #298 are the targets of this change.  I did not hear back from the authors of those issues but my own testing shows this to be an intermittent problem that is fixed.
2. New hardware revision decode scheme addresses issues #266 and #316.  This change was tested by the authors of those issues and reported to work on 64-bit OS.  My own testing found an issue with a legacy revision code and this was subsequently fixed.  My testing covered all generations of raspberry pi **except** Pi4 (I don't own this hw, yet).  Mostly for …

Release v74

---

pigpio.3
pigpio.c
pigpio.h
pigpio.py
pigpiod_if2.3
pigpiod_if2.c
pigpiod_if2.h
pigs.1
setup.py

Added code for BSC I2C/SPI slave on the BCM2711 (PI4B) and corrected an error in GPIO mode
setting for SPI as slave which existed in the earlier implementation.
Added explanatory documentation for callback usage.

Bcm2711 bsc slave

---

pigpio.c

During study of your library I saw the constant mismatch.
Just corrected it, even it has no effect, both #defines have actually the same value

Corrected constant name in spiClose from PI_I2C_CLOSED to PI_SPI_CLOSED

---

CMakeLists.txt
cmake/FindRT.cmake
cmake/pigpioConfig.cmake
cmake/setup.py.in

The current cmake setup of the pigpio project was incompatible with a yocto build for the raspberry pi. For some reason it had problems finding standard header files like <stdio.h>. However the builds succeeded on non Yocto builds which reinforced my suspicion that the CMake setup was the cause.
Nevertheless I modernized the CMake setup, which now also builds in a yocto environment :D. The new CMake conforms with the current CMake 3.0 standard. As such the following features are available.
- Usage of CMAKE_INSTALL_PREFIX instead of the custom DEST_DIR
- Usage of CMAKE_BUILD_TYPE to determine Release/Debug or RelWithDebInfo builds.
- Usage of CMake versioning system
- Create a CMake importable package configuration for all configurations.
- Create a CMake installer via CPack (build the …

Fix cmake setup for yocto

---

pigpio.c

I've encountered `initPeripherals: mmap gpio failed(Operation not permitted)` due to PROT_EXEC on Ubuntu 20.04 64bit.
Remove PROT_EXEC from initMapMem.

Fix initPeripherals on Ubuntu 20.04

---

pigpiod_if2.c
pigpiod_if2.h
x_pigpiod_if2.c

PR related to issue #374 
This change will allow to use `pigpio_start` with string literals arguments. Current solution forbids it.
All tests from `x_pigpio, x_pigpiod_if2, x_pigpio.py, x_pigs, x_pipe` passed.
New test case added in `x_pigpiod_if2` to prove proper behavior of changed `pigpio_start` function.

Change argument type of `pigpio_start` from `char*` to `const char*`

---

EXAMPLES/Python/SENT_PROTOCOL/README.md
EXAMPLES/Python/SENT_PROTOCOL/read_SENT.py

Single edge nibble transmission (SENT) is an automotive standard single wire interface for robust communication
with sensors in a car, but the standard can be used anywhere for robust sensor communication.     It has error detection
including CRC checking and can send multiple channels of data on the same wire.     
This example started with the pigpio PWM example and expanded it to work with SENT.  The biggest addition was the 
addition of the threading module to allow complete 3us tick time SENT frames to be sampled and processed with the raspberry
pi.    
The code was tested on the raspberry pi zero with 3us and larger tick time SENT signal.  (3us is the smallest tick time of the standard)
There is a write up and short video about it on the
Blog: …

added an example of using pigpio to implement the SENT interface
